### ISSUE TITLE
Output function could be replaced with colorama/termcolor packages.

### ISSUE THREAD

**Issue by Sigmanificient** [Sunspire/TextAdventure#2]
Hi, while looking at your project i come across that following output function:

```py
def output(text, color_code):
    if color_codes.get(color_code) is None:
        return '\33[31mfuntions > general > output > Unknown color'

    return f'\33[{color_codes.get(color_code)}m{text}'
```

<hr>

I think that it would be better to use the `colorama` along the `termcolor` package to have a better support across os.
Here is a example on how you could use those 2 packages in order to remove completely that one above function.

```py
import colorama
from termcolor import colored

colorama.init()

print(colored("Lorem Ipsum", color='blue'))
```

Notice how similar that function is from yours ! 
If you need i can make a pull requests that would replace all output occurrences to avoid wasting your time.

feel free to check by clicking [here](https://github.com/Sigmanificient/TextAdventure/tree/colorama/termcolor)

Have a great day !

**Comment by Sunspire** [comment]
@Sigmanificient 
Awesome, thanks!
I will make the changes myself, else I will not learn.

**Comment by Sunspire** [comment]
Output() function has been replace with Colorama and Termcolor

**Comment by Sigmanificient** [comment]
Great job !
